from aq_geometric.models.base_model import BaseModel
from aq_geometric.models.torch.base_model import TorchBaseModelAdapter
from aq_geometric.models.torch.edge_conv import EdgeConv, EdgeConvModel
from aq_geometric.models.torch.gcn import GCNModel
from aq_geometric.models.torch.hierarchical_edge_conv.heirarchical_edge_conv import AqHierarchicalEdgeConvModel, process_aq_geometric_dataset_edges_by_h3_resolution
from aq_geometric.models.torch.message_passing.message_passing import AqGeometricMessagePassingModel
from aq_geometric.models.xgboost.hierarchical_xgb.hierarchical_xgb_direct import AqGeometricXGBModel
from aq_geometric.models.xgboost.hierarchical_xgb.hierarchical_xgb_iterative import AqGeometricXGBIterativeModel
from aq_geometric.models.statistical_baselines.persistance.persistance import AqGeometricPersistanceModel
from aq_geometric.models.statistical_baselines.climatology.climatology import AqGeometricClimatologyModel
from aq_geometric.models.statistical_baselines.temporal.temporal import AqGeometricTemporalModel
from aq_geometric.models.statistical_baselines.linear.linear import AqGeometricLinearModel
