__name__ = 'florentino'
__version__ = '0.0.0.1'
__author__ = 'Nguyen Tuong Ha'
__maintainer__ = 'Florentino Developers'
__maintainer_email__ = 'hatuongnguyen0107@gmail.com'
__description__ = 'I am obsessed with coding from scratch, so I only use Numpy for implementing this AI package.'
__url__ = 'https://github.com/nguyenpanda'
__python_requires__ = '>=3.9'
__src__ = 'https://github.com/nguyenpanda/florentino'
__license__ = 'Apache License 2.0'
