def create(source: str, link_name: str) -> None:
    """
    Create a junction at link_name pointing to source.
    """

def isjunction(path: str) -> bool: ...
def readlink(path: str) -> str: ...
def unlink(path: str) -> None: ...
