# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_rs_open_model_parameters_bolt_shear_type_idea_rs_open_model import IdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel

class TestIdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel(unittest.TestCase):
    """IdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel(self):
        """Test IdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel"""
        # inst = IdeaRSOpenModelParametersBoltShearTypeIdeaRSOpenModel()

if __name__ == '__main__':
    unittest.main()
