# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_rs_connections_data_shear_force_transfer_methods_ci_basic_types import IdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes

class TestIdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes(unittest.TestCase):
    """IdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes(self):
        """Test IdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes"""
        # inst = IdeaRSConnectionsDataShearForceTransferMethodsCIBasicTypes()

if __name__ == '__main__':
    unittest.main()
