# Generated by Django 5.0.7 on 2024-07-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sage_seo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metainformation",
            name="og_description",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="og_title",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="og_type",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="twitter_card",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="twitter_creator",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="twitter_image",
        ),
        migrations.RemoveField(
            model_name="metainformation",
            name="twitter_site",
        ),
    ]
