# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_stati_ca_connection_basic_types_data_anchor_tensile_calculation_ausci_basic_types import IdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes

class TestIdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes(unittest.TestCase):
    """IdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes(self):
        """Test IdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes"""
        # inst = IdeaStatiCaConnectionBasicTypesDataAnchorTensileCalculationAUSCIBasicTypes()

if __name__ == '__main__':
    unittest.main()
