# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_stati_ca_connection_basic_types_data_detailing_check_category_ci_basic_types import IdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes

class TestIdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes(unittest.TestCase):
    """IdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes(self):
        """Test IdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes"""
        # inst = IdeaStatiCaConnectionBasicTypesDataDetailingCheckCategoryCIBasicTypes()

if __name__ == '__main__':
    unittest.main()
