# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_rs_open_model_connection_connection_check_res_idea_rs_open_model import IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel

class TestIdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel(unittest.TestCase):
    """IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel:
        """Test IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel`
        """
        model = IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel()
        if include_optional:
            return IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel(
                check_res_summary = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_summary_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResSummary-IdeaRS_OpenModel(
                        check_value = 1.337, 
                        check_status = True, 
                        load_case_id = 56, 
                        name = '', 
                        unity_check_message = '', 
                        skipped = True, )
                    ],
                check_res_plate = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_plate_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResPlate-IdeaRS_OpenModel(
                        name = '', 
                        check_status = True, 
                        load_case_id = 56, 
                        max_strain = 1.337, 
                        max_stress = 1.337, 
                        items = [
                            56
                            ], )
                    ],
                check_res_weld = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_weld_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResWeld-IdeaRS_OpenModel(
                        name = '', 
                        id = 56, 
                        unity_check = 1.337, 
                        check_status = True, 
                        load_case_id = 56, 
                        items = [
                            56
                            ], )
                    ],
                check_res_bolt = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_bolt_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResBolt-IdeaRS_OpenModel(
                        name = '', 
                        unity_check = 1.337, 
                        check_status = True, )
                    ],
                check_res_anchor = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_anchor_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResAnchor-IdeaRS_OpenModel(
                        name = '', 
                        unity_check = 1.337, 
                        check_status = True, )
                    ],
                check_res_concrete_block = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_check_res_concrete_block_idea_rs_open_model.IdeaRS_OpenModel_Connection_CheckResConcreteBlock-IdeaRS_OpenModel(
                        name = '', 
                        unity_check = 1.337, 
                        check_status = True, 
                        load_case_id = 56, )
                    ],
                buckling_results = [
                    connection_restapi_client_poc.models.idea_rs_open_model_connection_buckling_res_idea_rs_open_model.IdeaRS_OpenModel_Connection_BucklingRes-IdeaRS_OpenModel(
                        load_case_id = 56, 
                        shape = 56, 
                        factor = 1.337, )
                    ],
                name = '',
                connection_id = '',
                id = 56,
                messages = connection_restapi_client_poc.models.idea_rs_open_model_message_open_messages_idea_rs_open_model.IdeaRS_OpenModel_Message_OpenMessages-IdeaRS_OpenModel(
                    messages = [
                        connection_restapi_client_poc.models.idea_rs_open_model_message_open_message_idea_rs_open_model.IdeaRS_OpenModel_Message_OpenMessage-IdeaRS_OpenModel(
                            number = 'unspecified', 
                            description = '', )
                        ], )
            )
        else:
            return IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel(
        )
        """

    def testIdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel(self):
        """Test IdeaRSOpenModelConnectionConnectionCheckResIdeaRSOpenModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
