# coding: utf-8

"""
    Connection Rest API 1.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from connection_restapi_client_poc.models.idea_rs_open_model_detail_solid_block3_d_idea_rs_open_model import IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel

class TestIdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel(unittest.TestCase):
    """IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel:
        """Test IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel`
        """
        model = IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel()
        if include_optional:
            return IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel(
                id = 56
            )
        else:
            return IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel(
        )
        """

    def testIdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel(self):
        """Test IdeaRSOpenModelDetailSolidBlock3DIdeaRSOpenModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
