
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-30T16:01:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a72a8f758e3a251ad5198198d63fb7497a9c468",
 "version": "2024.7.30.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
