class rftbRegs:
    SYS_UPTIME = "SYS_UPTIME"
    SYS_REGMAP_VERSION = "SYS_REGMAP_VERSION"
    SYS_STATUS = "SYS_STATUS"
    SYS_ERROR = "SYS_ERROR"
    SYS_COMMAND = "SYS_COMMAND"
    SYS_WARM_UP_TIME = "SYS_WARM_UP_TIME"
    SYS_BOOT_STATUS = "SYS_BOOT_STATUS"
    SYS_LOG_LEVEL = "SYS_LOG_LEVEL"
    SYS_TEST = "SYS_TEST"
    FACT_SERIAL_NUMBER = "FACT_SERIAL_NUMBER"
    FACT_DEVICE_ID = "FACT_DEVICE_ID"
    FACT_HW_REVISION = "FACT_HW_REVISION"
    FACT_BOOT_REVISION = "FACT_BOOT_REVISION"
    FIRM_REVISION = "FIRM_REVISION"
    FIRM_ASSEMBLY_INFO = "FIRM_ASSEMBLY_INFO"
    FIRM_APP_CHECKSUM = "FIRM_APP_CHECKSUM"
    FIRM_APP_SIZE = "FIRM_APP_SIZE"
    ANL_AD1 = "ANL_AD1"
    ANL_AD2 = "ANL_AD2"
    ANL_AD3 = "ANL_AD3"
    ANL_VREF_MCU = "ANL_VREF_MCU"
    ANL_TEMP_MCU = "ANL_TEMP_MCU"
    ANL_CSR = "ANL_CSR"
    ANL_RESERVED = "ANL_RESERVED"
    ANL_DA1 = "ANL_DA1"
    ANL_DA2 = "ANL_DA2"
    RFA_FREQ_BASE = "RFA_FREQ_BASE"
    RFA_CFG_PROFILE = "RFA_CFG_PROFILE"
    RFA_OUTPUT_POWER = "RFA_OUTPUT_POWER"
    RFA_RX_RSSI_THR = "RFA_RX_RSSI_THR"
    RFA_RUN_RSSI = "RFA_RUN_RSSI"
    RFA_LAST_RSSI = "RFA_LAST_RSSI"
    RFA_FREQ_ERROR = "RFA_FREQ_ERROR"
    RFB_TX_DATA = "RFB_TX_DATA"
    RFB_RX_DATA = "RFB_RX_DATA"
    RFB_MSG_LENGTH = "RFB_MSG_LENGTH"
    RFB_CYCLE_COUNT = "RFB_CYCLE_COUNT"
    RFB_TX_INTERVAL = "RFB_TX_INTERVAL"
    RFB_RX_DIFFTIME = "RFB_RX_DIFFTIME"
    RFB_TX_PACKETS = "RFB_TX_PACKETS"
    RFB_RX_PACKETS = "RFB_RX_PACKETS"
    RFB_BITS = "RFB_BITS"
    RFB_ERRORS = "RFB_ERRORS"
    RFB_GENERIC = "RFB_GENERIC"
    RFB_CYCLE_NUM = "RFB_CYCLE_NUM"
    RFC_CSR = "RFC_CSR"
    RFC_MODE = "RFC_MODE"
    RFC_CALIB_MEASURE_TIME = "RFC_CALIB_MEASURE_TIME"
    RFC_FREQ_SHIFT = "RFC_FREQ_SHIFT"
    RFC_FREQUENCY_A = "RFC_FREQUENCY_A"
    RFC_FREQUENCY_B = "RFC_FREQUENCY_B"
    RFC_OUTPUT_POWER_DBM = "RFC_OUTPUT_POWER_DBM"
    RFC_RUN_RSSI_DBM = "RFC_RUN_RSSI_DBM"
    RFC_LAST_RSSI_DBM = "RFC_LAST_RSSI_DBM"
    RFC_RF_LEVEL_DBM = "RFC_RF_LEVEL_DBM"
    RFC_AVG_RSSI_TST = "RFC_AVG_RSSI_TST"
    RFC_AVG_RSSI_DUT = "RFC_AVG_RSSI_DUT"
    RFC_AVG_AFC_TST = "RFC_AVG_AFC_TST"
    RFC_RESP_NUM = "RFC_RESP_NUM"
    CLK_MCO1_ENABLE = "CLK_MCO1_ENABLE"
    CLK_MCO2_ENABLE = "CLK_MCO2_ENABLE"
    CLK_SAI1_ENABLE = "CLK_SAI1_ENABLE"
    CLK_SAI2_ENABLE = "CLK_SAI2_ENABLE"
    CLK_MCO1_FREQUENCY = "CLK_MCO1_FREQUENCY"
    CLK_MCO2_FREQUENCY = "CLK_MCO2_FREQUENCY"
    CLK_SAI1_FREQUENCY = "CLK_SAI1_FREQUENCY"
    CLK_SAI2_FREQUENCY = "CLK_SAI2_FREQUENCY"
    CAL_FREQ_OFFSET = "CAL_FREQ_OFFSET"
    CAL_MEAS_SENS = "CAL_MEAS_SENS"
    CAL_MEAS_OFFSET = "CAL_MEAS_OFFSET"
    CAL_INPUT_OFFSET = "CAL_INPUT_OFFSET"
    CAL_SRC_SENS = "CAL_SRC_SENS"
    CAL_SRC_OFFSET = "CAL_SRC_OFFSET"
    CAL_RSSI_OFFSET = "CAL_RSSI_OFFSET"
    CAL_CHECKSUM = "CAL_CHECKSUM"
    CAL_RESERVED = "CAL_RESERVED"
    CAL_STATUS = "CAL_STATUS"
    CAL_RESERVED_1 = "CAL_RESERVED_1"
    COM_MB_BAUD_RATE = "COM_MB_BAUD_RATE"
    COM_MB_PARITY = "COM_MB_PARITY"
    COM_MB_STOP_BITS = "COM_MB_STOP_BITS"
    COM_RESERVED = "COM_RESERVED"
    COM_MB_ADDRESS = "COM_MB_ADDRESS"
    COM_MB_APPLY = "COM_MB_APPLY"
    SLF_FREQUENCY = "SLF_FREQUENCY"
    SLF_LEVEL_BG_LIMIT = "SLF_LEVEL_BG_LIMIT"
    SLF_START_DELAY = "SLF_START_DELAY"
    SLF_POWER_SETTING = "SLF_POWER_SETTING"
    SLF_MEAS_CYCLES = "SLF_MEAS_CYCLES"
    SLF_LEVEL_ERROR_LIMIT = "SLF_LEVEL_ERROR_LIMIT"
    SLF_LEVEL_SPAN_LIMIT = "SLF_LEVEL_SPAN_LIMIT"
    SLF_LEVEL_BG = "SLF_LEVEL_BG"
    SLF_LEVEL_ERROR = "SLF_LEVEL_ERROR"
    SLF_LEVEL_SPAN = "SLF_LEVEL_SPAN"
    SLF_VREF = "SLF_VREF"
    SLF_VREF_LIMIT_UP = "SLF_VREF_LIMIT_UP"
    SLF_VREF_LIMIT_DOWN = "SLF_VREF_LIMIT_DOWN"
    SLF_VCC = "SLF_VCC"
    SLF_VCC_LIMIT_UP = "SLF_VCC_LIMIT_UP"
    SLF_VCC_LIMIT_DOWN = "SLF_VCC_LIMIT_DOWN"
    SLF_VSMPS = "SLF_VSMPS"
    SLF_VSMPS_LIMIT_UP = "SLF_VSMPS_LIMIT_UP"
    SLF_VSMPS_LIMIT_DOWN = "SLF_VSMPS_LIMIT_DOWN"
    SLF_RESERVED = "SLF_RESERVED"
    SLF_DBG_0 = "SLF_DBG_0"
    SLF_DBG_1 = "SLF_DBG_1"


class ANL_CSR:
    ANL_NONE = 0
    ANL_UPDATE = 1
    ANL_CALIBRATE = 2


class RFA_CFG_PROFILE:
    RF_CFG_TP = 0
    RF_CFG_DHW = 1
    RF_CFG_RT = 2


class RFB_TX_DATA:
    TX_MSG_TP15X = 0
    TX_MSG_DHW = 1
    TX_MSG_RT = 2


class RFB_RX_DATA:
    RX_MSG_RX2TX = 0
    RX_MSG_DHW = 1


class RFC_CSR:
    RFS_READY = 0
    RFS_LEVEL = 1
    RFS_FREQ_A = 2
    RFS_FREQ_B = 3
    RFS_FREQ_CALC = 4
    RFS_BUSY = 5
    RFS_ERROR = 6
    RFS_CHECK = 7


class RFC_MODE:
    RM_READY = 0
    RM_CW = 1
    RM_RX = 2
    RM_TX = 3
    RM_TRX = 4


class CAL_STATUS:
    CAL_STATUS_NONE = 0
    CAL_STATUS_SUCCEED = 1
    CAL_STATUS_FAILED = 2


class COM_MB_BAUD_RATE:
    MB_BAUD_9600 = 0
    MB_BAUD_19200 = 1
    MB_BAUD_38400 = 2
    MB_BAUD_57600 = 3
    MB_BAUD_115200 = 4


class COM_MB_PARITY:
    MB_PARITY_NONE = 0
    MB_PARITY_EVEN = 1
    MB_PARITY_ODD = 2


class COM_MB_STOP_BITS:
    MB_STOP_1 = 0
    MB_STOP_2 = 1


