# coding: utf-8
"""
    Test Automation (No submodules)

    SDKs (no submodules) to test automation workflows.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from automation_test_with_submodule.paths.hello.get import Hello
from automation_test_with_submodule.apis.tags.greetings_api_raw import GreetingsApiRaw


class GreetingsApiGenerated(
    Hello,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GreetingsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GreetingsApiRaw(api_client)
