# Generated by Django 4.1.4 on 2023-07-14 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model_app', '0628_merge_20230712_1620'),
        ('asu_ods_integration', '0002_asuodstransport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuodstransport',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AlterField(
            model_name='asuodstransport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалено'),
        ),
        migrations.AlterField(
            model_name='asuodstransport',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_%(class)s', to='model_app.participant', verbose_name='Владелец'),
        ),
    ]
