"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cohesity_sdk.cluster.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from cohesity_sdk.cluster.model.aws_object_protection_request_params import AwsObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.azure_object_protection_request_params import AzureObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.common_env_specific_object_protection_params import CommonEnvSpecificObjectProtectionParams
    from cohesity_sdk.cluster.model.elastifile_object_protection_request_params import ElastifileObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.env_specific_object_protection_request_params_all_of import EnvSpecificObjectProtectionRequestParamsAllOf
    from cohesity_sdk.cluster.model.flashblade_object_protection_request_params import FlashbladeObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.generic_nas_object_protection_request_params import GenericNasObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.gpfs_object_protection_request_params import GpfsObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.hyper_v_object_protection_request_params import HyperVObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.isilon_object_protection_request_params import IsilonObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.mssql_object_protection_request_params import MssqlObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.netapp_object_protection_request_params import NetappObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.office365_object_protection_request_params import Office365ObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.oracle_object_protection_request_params import OracleObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.physical_object_protection_request_params import PhysicalObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.sfdc_object_protection_request_params import SfdcObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.uda_object_protection_request_params import UdaObjectProtectionRequestParams
    from cohesity_sdk.cluster.model.vmware_object_protection_request_params import VmwareObjectProtectionRequestParams
    globals()['AwsObjectProtectionRequestParams'] = AwsObjectProtectionRequestParams
    globals()['AzureObjectProtectionRequestParams'] = AzureObjectProtectionRequestParams
    globals()['CommonEnvSpecificObjectProtectionParams'] = CommonEnvSpecificObjectProtectionParams
    globals()['ElastifileObjectProtectionRequestParams'] = ElastifileObjectProtectionRequestParams
    globals()['EnvSpecificObjectProtectionRequestParamsAllOf'] = EnvSpecificObjectProtectionRequestParamsAllOf
    globals()['FlashbladeObjectProtectionRequestParams'] = FlashbladeObjectProtectionRequestParams
    globals()['GenericNasObjectProtectionRequestParams'] = GenericNasObjectProtectionRequestParams
    globals()['GpfsObjectProtectionRequestParams'] = GpfsObjectProtectionRequestParams
    globals()['HyperVObjectProtectionRequestParams'] = HyperVObjectProtectionRequestParams
    globals()['IsilonObjectProtectionRequestParams'] = IsilonObjectProtectionRequestParams
    globals()['MssqlObjectProtectionRequestParams'] = MssqlObjectProtectionRequestParams
    globals()['NetappObjectProtectionRequestParams'] = NetappObjectProtectionRequestParams
    globals()['Office365ObjectProtectionRequestParams'] = Office365ObjectProtectionRequestParams
    globals()['OracleObjectProtectionRequestParams'] = OracleObjectProtectionRequestParams
    globals()['PhysicalObjectProtectionRequestParams'] = PhysicalObjectProtectionRequestParams
    globals()['SfdcObjectProtectionRequestParams'] = SfdcObjectProtectionRequestParams
    globals()['UdaObjectProtectionRequestParams'] = UdaObjectProtectionRequestParams
    globals()['VmwareObjectProtectionRequestParams'] = VmwareObjectProtectionRequestParams


class EnvSpecificObjectProtectionRequestParams(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.

      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.

    """

    allowed_values = {
        ('environment',): {
            'None': None,
            'KVMWARE': "kVMware",
            'KHYPERV': "kHyperV",
            'KVCD': "kVCD",
            'KAZURE': "kAzure",
            'KGCP': "kGCP",
            'KKVM': "kKVM",
            'KACROPOLIS': "kAcropolis",
            'KAWS': "kAWS",
            'KAWSNATIVE': "kAWSNative",
            'KAWSS3': "kAwsS3",
            'KAWSSNAPSHOTMANAGER': "kAWSSnapshotManager",
            'KRDSSNAPSHOTMANAGER': "kRDSSnapshotManager",
            'KAURORASNAPSHOTMANAGER': "kAuroraSnapshotManager",
            'KAWSRDSPOSTGRESBACKUP': "kAwsRDSPostgresBackup",
            'KAZURENATIVE': "kAzureNative",
            'KAZURESQL': "kAzureSQL",
            'KAZURESNAPSHOTMANAGER': "kAzureSnapshotManager",
            'KPHYSICAL': "kPhysical",
            'KPHYSICALFILES': "kPhysicalFiles",
            'KGPFS': "kGPFS",
            'KELASTIFILE': "kElastifile",
            'KNETAPP': "kNetapp",
            'KGENERICNAS': "kGenericNas",
            'KISILON': "kIsilon",
            'KFLASHBLADE': "kFlashBlade",
            'KPURE': "kPure",
            'KIBMFLASHSYSTEM': "kIbmFlashSystem",
            'KSQL': "kSQL",
            'KEXCHANGE': "kExchange",
            'KAD': "kAD",
            'KORACLE': "kOracle",
            'KVIEW': "kView",
            'KREMOTEADAPTER': "kRemoteAdapter",
            'KO365': "kO365",
            'KO365PUBLICFOLDERS': "kO365PublicFolders",
            'KO365TEAMS': "kO365Teams",
            'KO365GROUP': "kO365Group",
            'KO365EXCHANGE': "kO365Exchange",
            'KO365ONEDRIVE': "kO365OneDrive",
            'KO365SHAREPOINT': "kO365Sharepoint",
            'KKUBERNETES': "kKubernetes",
            'KCASSANDRA': "kCassandra",
            'KMONGODB': "kMongoDB",
            'KCOUCHBASE': "kCouchbase",
            'KHDFS': "kHdfs",
            'KHIVE': "kHive",
            'KHBASE': "kHBase",
            'KUDA': "kUDA",
            'KSFDC': "kSfdc",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'environment': (str, none_type,),  # noqa: E501
            'aws_params': (AwsObjectProtectionRequestParams,),  # noqa: E501
            'azure_params': (AzureObjectProtectionRequestParams,),  # noqa: E501
            'elastifile_params': (ElastifileObjectProtectionRequestParams,),  # noqa: E501
            'flashblade_params': (FlashbladeObjectProtectionRequestParams,),  # noqa: E501
            'generic_nas_params': (GenericNasObjectProtectionRequestParams,),  # noqa: E501
            'gpfs_params': (GpfsObjectProtectionRequestParams,),  # noqa: E501
            'hyperv_params': (HyperVObjectProtectionRequestParams,),  # noqa: E501
            'isilon_params': (IsilonObjectProtectionRequestParams,),  # noqa: E501
            'mssql_params': (MssqlObjectProtectionRequestParams,),  # noqa: E501
            'netapp_params': (NetappObjectProtectionRequestParams,),  # noqa: E501
            'office365_params': (Office365ObjectProtectionRequestParams,),  # noqa: E501
            'oracle_params': (OracleObjectProtectionRequestParams,),  # noqa: E501
            'physical_params': (PhysicalObjectProtectionRequestParams,),  # noqa: E501
            'sfdc_params': (SfdcObjectProtectionRequestParams,),  # noqa: E501
            'uda_params': (UdaObjectProtectionRequestParams,),  # noqa: E501
            'vmware_params': (VmwareObjectProtectionRequestParams,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None



    attribute_map = {
        'environment': 'environment',  # noqa: E501
        'aws_params': 'awsParams',  # noqa: E501
        'azure_params': 'azureParams',  # noqa: E501
        'elastifile_params': 'elastifileParams',  # noqa: E501
        'flashblade_params': 'flashbladeParams',  # noqa: E501
        'generic_nas_params': 'genericNasParams',  # noqa: E501
        'gpfs_params': 'gpfsParams',  # noqa: E501
        'hyperv_params': 'hypervParams',  # noqa: E501
        'isilon_params': 'isilonParams',  # noqa: E501
        'mssql_params': 'mssqlParams',  # noqa: E501
        'netapp_params': 'netappParams',  # noqa: E501
        'office365_params': 'office365Params',  # noqa: E501
        'oracle_params': 'oracleParams',  # noqa: E501
        'physical_params': 'physicalParams',  # noqa: E501
        'sfdc_params': 'sfdcParams',  # noqa: E501
        'uda_params': 'udaParams',  # noqa: E501
        'vmware_params': 'vmwareParams',  # noqa: E501
    }

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """EnvSpecificObjectProtectionRequestParams - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)

            environment (str, none_type): Specifies the environment for current object.. [optional]  # noqa: E501
            aws_params (AwsObjectProtectionRequestParams): [optional]  # noqa: E501
            azure_params (AzureObjectProtectionRequestParams): [optional]  # noqa: E501
            elastifile_params (ElastifileObjectProtectionRequestParams): [optional]  # noqa: E501
            flashblade_params (FlashbladeObjectProtectionRequestParams): [optional]  # noqa: E501
            generic_nas_params (GenericNasObjectProtectionRequestParams): [optional]  # noqa: E501
            gpfs_params (GpfsObjectProtectionRequestParams): [optional]  # noqa: E501
            hyperv_params (HyperVObjectProtectionRequestParams): [optional]  # noqa: E501
            isilon_params (IsilonObjectProtectionRequestParams): [optional]  # noqa: E501
            mssql_params (MssqlObjectProtectionRequestParams): [optional]  # noqa: E501
            netapp_params (NetappObjectProtectionRequestParams): [optional]  # noqa: E501
            office365_params (Office365ObjectProtectionRequestParams): [optional]  # noqa: E501
            oracle_params (OracleObjectProtectionRequestParams): [optional]  # noqa: E501
            physical_params (PhysicalObjectProtectionRequestParams): [optional]  # noqa: E501
            sfdc_params (SfdcObjectProtectionRequestParams): [optional]  # noqa: E501
            uda_params (UdaObjectProtectionRequestParams): [optional]  # noqa: E501
            vmware_params (VmwareObjectProtectionRequestParams): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)


        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        required_args = {
        }
        model_args = {}
        model_args.update(required_args)
        model_args.update(kwargs)
        composed_info = validate_get_composed_info(
            constant_args, model_args, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        unused_args = composed_info[3]

        for var_name, var_value in required_args.items():
            setattr(self, var_name, var_value)
        for var_name, var_value in kwargs.items():
            if var_name in unused_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        not self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)


    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error beause the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
              CommonEnvSpecificObjectProtectionParams,
              EnvSpecificObjectProtectionRequestParamsAllOf,
          ],
          'oneOf': [
          ],
        }

