"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cohesity_sdk.cluster.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from cohesity_sdk.cluster.model.aws_object_protection_response_params import AwsObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.azure_object_protection_response_params import AzureObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.elastifile_object_protection_response_params import ElastifileObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.flashblade_object_protection_response_params import FlashbladeObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.generic_nas_object_protection_response_params import GenericNasObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.gpfs_object_protection_response_params import GpfsObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.hyper_v_object_protection_response_params import HyperVObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.isilon_object_protection_response_params import IsilonObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.mssql_object_protection_response_params import MssqlObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.netapp_object_protection_response_params import NetappObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.office365_object_protection_response_params import Office365ObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.oracle_object_protection_response_params import OracleObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.physical_object_protection_response_params import PhysicalObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.sfdc_object_protection_response_params import SfdcObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.uda_object_protection_response_params import UdaObjectProtectionResponseParams
    from cohesity_sdk.cluster.model.vmware_object_protection_response_params import VmwareObjectProtectionResponseParams
    globals()['AwsObjectProtectionResponseParams'] = AwsObjectProtectionResponseParams
    globals()['AzureObjectProtectionResponseParams'] = AzureObjectProtectionResponseParams
    globals()['ElastifileObjectProtectionResponseParams'] = ElastifileObjectProtectionResponseParams
    globals()['FlashbladeObjectProtectionResponseParams'] = FlashbladeObjectProtectionResponseParams
    globals()['GenericNasObjectProtectionResponseParams'] = GenericNasObjectProtectionResponseParams
    globals()['GpfsObjectProtectionResponseParams'] = GpfsObjectProtectionResponseParams
    globals()['HyperVObjectProtectionResponseParams'] = HyperVObjectProtectionResponseParams
    globals()['IsilonObjectProtectionResponseParams'] = IsilonObjectProtectionResponseParams
    globals()['MssqlObjectProtectionResponseParams'] = MssqlObjectProtectionResponseParams
    globals()['NetappObjectProtectionResponseParams'] = NetappObjectProtectionResponseParams
    globals()['Office365ObjectProtectionResponseParams'] = Office365ObjectProtectionResponseParams
    globals()['OracleObjectProtectionResponseParams'] = OracleObjectProtectionResponseParams
    globals()['PhysicalObjectProtectionResponseParams'] = PhysicalObjectProtectionResponseParams
    globals()['SfdcObjectProtectionResponseParams'] = SfdcObjectProtectionResponseParams
    globals()['UdaObjectProtectionResponseParams'] = UdaObjectProtectionResponseParams
    globals()['VmwareObjectProtectionResponseParams'] = VmwareObjectProtectionResponseParams


class EnvSpecificObjectProtectionResponseParams(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.

      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.

    """

    allowed_values = {
        ('environment',): {
            'None': None,
            'KVMWARE': "kVMware",
            'KHYPERV': "kHyperV",
            'KVCD': "kVCD",
            'KAZURE': "kAzure",
            'KGCP': "kGCP",
            'KKVM': "kKVM",
            'KACROPOLIS': "kAcropolis",
            'KAWS': "kAWS",
            'KAWSNATIVE': "kAWSNative",
            'KAWSS3': "kAwsS3",
            'KAWSSNAPSHOTMANAGER': "kAWSSnapshotManager",
            'KRDSSNAPSHOTMANAGER': "kRDSSnapshotManager",
            'KAURORASNAPSHOTMANAGER': "kAuroraSnapshotManager",
            'KAWSRDSPOSTGRESBACKUP': "kAwsRDSPostgresBackup",
            'KAZURENATIVE': "kAzureNative",
            'KAZURESQL': "kAzureSQL",
            'KAZURESNAPSHOTMANAGER': "kAzureSnapshotManager",
            'KPHYSICAL': "kPhysical",
            'KPHYSICALFILES': "kPhysicalFiles",
            'KGPFS': "kGPFS",
            'KELASTIFILE': "kElastifile",
            'KNETAPP': "kNetapp",
            'KGENERICNAS': "kGenericNas",
            'KISILON': "kIsilon",
            'KFLASHBLADE': "kFlashBlade",
            'KPURE': "kPure",
            'KIBMFLASHSYSTEM': "kIbmFlashSystem",
            'KSQL': "kSQL",
            'KEXCHANGE': "kExchange",
            'KAD': "kAD",
            'KORACLE': "kOracle",
            'KVIEW': "kView",
            'KREMOTEADAPTER': "kRemoteAdapter",
            'KO365': "kO365",
            'KO365PUBLICFOLDERS': "kO365PublicFolders",
            'KO365TEAMS': "kO365Teams",
            'KO365GROUP': "kO365Group",
            'KO365EXCHANGE': "kO365Exchange",
            'KO365ONEDRIVE': "kO365OneDrive",
            'KO365SHAREPOINT': "kO365Sharepoint",
            'KKUBERNETES': "kKubernetes",
            'KCASSANDRA': "kCassandra",
            'KMONGODB': "kMongoDB",
            'KCOUCHBASE': "kCouchbase",
            'KHDFS': "kHdfs",
            'KHIVE': "kHive",
            'KHBASE': "kHBase",
            'KUDA': "kUDA",
            'KSFDC': "kSfdc",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'aws_params': (AwsObjectProtectionResponseParams,),  # noqa: E501
            'azure_params': (AzureObjectProtectionResponseParams,),  # noqa: E501
            'elastifile_params': (ElastifileObjectProtectionResponseParams,),  # noqa: E501
            'environment': (str, none_type,),  # noqa: E501
            'flashblade_params': (FlashbladeObjectProtectionResponseParams,),  # noqa: E501
            'generic_nas_params': (GenericNasObjectProtectionResponseParams,),  # noqa: E501
            'gpfs_params': (GpfsObjectProtectionResponseParams,),  # noqa: E501
            'hyperv_params': (HyperVObjectProtectionResponseParams,),  # noqa: E501
            'isilon_params': (IsilonObjectProtectionResponseParams,),  # noqa: E501
            'mssql_params': (MssqlObjectProtectionResponseParams,),  # noqa: E501
            'netapp_params': (NetappObjectProtectionResponseParams,),  # noqa: E501
            'office365_params': (Office365ObjectProtectionResponseParams,),  # noqa: E501
            'oracle_params': (OracleObjectProtectionResponseParams,),  # noqa: E501
            'physical_params': (PhysicalObjectProtectionResponseParams,),  # noqa: E501
            'sfdc_params': (SfdcObjectProtectionResponseParams,),  # noqa: E501
            'uda_params': (UdaObjectProtectionResponseParams,),  # noqa: E501
            'vmware_params': (VmwareObjectProtectionResponseParams,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None



    attribute_map = {
        'aws_params': 'awsParams',  # noqa: E501
        'azure_params': 'azureParams',  # noqa: E501
        'elastifile_params': 'elastifileParams',  # noqa: E501
        'environment': 'environment',  # noqa: E501
        'flashblade_params': 'flashbladeParams',  # noqa: E501
        'generic_nas_params': 'genericNasParams',  # noqa: E501
        'gpfs_params': 'gpfsParams',  # noqa: E501
        'hyperv_params': 'hypervParams',  # noqa: E501
        'isilon_params': 'isilonParams',  # noqa: E501
        'mssql_params': 'mssqlParams',  # noqa: E501
        'netapp_params': 'netappParams',  # noqa: E501
        'office365_params': 'office365Params',  # noqa: E501
        'oracle_params': 'oracleParams',  # noqa: E501
        'physical_params': 'physicalParams',  # noqa: E501
        'sfdc_params': 'sfdcParams',  # noqa: E501
        'uda_params': 'udaParams',  # noqa: E501
        'vmware_params': 'vmwareParams',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """EnvSpecificObjectProtectionResponseParams - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)

            aws_params (AwsObjectProtectionResponseParams): [optional]  # noqa: E501
            azure_params (AzureObjectProtectionResponseParams): [optional]  # noqa: E501
            elastifile_params (ElastifileObjectProtectionResponseParams): [optional]  # noqa: E501
            environment (str, none_type): Specifies the environment for current object.. [optional]  # noqa: E501
            flashblade_params (FlashbladeObjectProtectionResponseParams): [optional]  # noqa: E501
            generic_nas_params (GenericNasObjectProtectionResponseParams): [optional]  # noqa: E501
            gpfs_params (GpfsObjectProtectionResponseParams): [optional]  # noqa: E501
            hyperv_params (HyperVObjectProtectionResponseParams): [optional]  # noqa: E501
            isilon_params (IsilonObjectProtectionResponseParams): [optional]  # noqa: E501
            mssql_params (MssqlObjectProtectionResponseParams): [optional]  # noqa: E501
            netapp_params (NetappObjectProtectionResponseParams): [optional]  # noqa: E501
            office365_params (Office365ObjectProtectionResponseParams): [optional]  # noqa: E501
            oracle_params (OracleObjectProtectionResponseParams): [optional]  # noqa: E501
            physical_params (PhysicalObjectProtectionResponseParams): [optional]  # noqa: E501
            sfdc_params (SfdcObjectProtectionResponseParams): [optional]  # noqa: E501
            uda_params (UdaObjectProtectionResponseParams): [optional]  # noqa: E501
            vmware_params (VmwareObjectProtectionResponseParams): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)


        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)


