"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.hdfs_search_params import HdfsSearchParams
from cohesity_sdk.cluster.model.on_prem_source_ids import OnPremSourceIds
globals()['HdfsSearchParams'] = HdfsSearchParams
globals()['OnPremSourceIds'] = OnPremSourceIds
from cohesity_sdk.model.hdfson_prem_search_params import HDFSOnPremSearchParams


class TestHDFSOnPremSearchParams(unittest.TestCase):
    """HDFSOnPremSearchParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHDFSOnPremSearchParams(self):
        """Test HDFSOnPremSearchParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HDFSOnPremSearchParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
