"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.aws_object_protection_update_request_params import AwsObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.azure_object_protection_update_request_params import AzureObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.elastifile_object_protection_update_request_params import ElastifileObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.flashblade_object_protection_update_request_params import FlashbladeObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.generic_nas_object_protection_update_request_params import GenericNasObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.gpfs_object_protection_update_request_params import GpfsObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.hyper_v_object_protection_update_request_params import HyperVObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.isilon_object_protection_update_request_params import IsilonObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.mssql_object_protection_update_request_params import MssqlObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.netapp_object_protection_update_request_params import NetappObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.office365_object_protection_update_request_params import Office365ObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.oracle_object_protection_update_request_params import OracleObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.physical_object_protection_update_request_params import PhysicalObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.sfdc_object_protection_update_request_params import SfdcObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.uda_object_protection_update_request_params import UdaObjectProtectionUpdateRequestParams
from cohesity_sdk.cluster.model.vmware_object_protection_update_request_params import VmwareObjectProtectionUpdateRequestParams
globals()['AwsObjectProtectionUpdateRequestParams'] = AwsObjectProtectionUpdateRequestParams
globals()['AzureObjectProtectionUpdateRequestParams'] = AzureObjectProtectionUpdateRequestParams
globals()['ElastifileObjectProtectionUpdateRequestParams'] = ElastifileObjectProtectionUpdateRequestParams
globals()['FlashbladeObjectProtectionUpdateRequestParams'] = FlashbladeObjectProtectionUpdateRequestParams
globals()['GenericNasObjectProtectionUpdateRequestParams'] = GenericNasObjectProtectionUpdateRequestParams
globals()['GpfsObjectProtectionUpdateRequestParams'] = GpfsObjectProtectionUpdateRequestParams
globals()['HyperVObjectProtectionUpdateRequestParams'] = HyperVObjectProtectionUpdateRequestParams
globals()['IsilonObjectProtectionUpdateRequestParams'] = IsilonObjectProtectionUpdateRequestParams
globals()['MssqlObjectProtectionUpdateRequestParams'] = MssqlObjectProtectionUpdateRequestParams
globals()['NetappObjectProtectionUpdateRequestParams'] = NetappObjectProtectionUpdateRequestParams
globals()['Office365ObjectProtectionUpdateRequestParams'] = Office365ObjectProtectionUpdateRequestParams
globals()['OracleObjectProtectionUpdateRequestParams'] = OracleObjectProtectionUpdateRequestParams
globals()['PhysicalObjectProtectionUpdateRequestParams'] = PhysicalObjectProtectionUpdateRequestParams
globals()['SfdcObjectProtectionUpdateRequestParams'] = SfdcObjectProtectionUpdateRequestParams
globals()['UdaObjectProtectionUpdateRequestParams'] = UdaObjectProtectionUpdateRequestParams
globals()['VmwareObjectProtectionUpdateRequestParams'] = VmwareObjectProtectionUpdateRequestParams
from cohesity_sdk.model.env_specific_object_protection_update_request_params import EnvSpecificObjectProtectionUpdateRequestParams


class TestEnvSpecificObjectProtectionUpdateRequestParams(unittest.TestCase):
    """EnvSpecificObjectProtectionUpdateRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvSpecificObjectProtectionUpdateRequestParams(self):
        """Test EnvSpecificObjectProtectionUpdateRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvSpecificObjectProtectionUpdateRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
