"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.keystone import Keystone
globals()['Keystone'] = Keystone
from cohesity_sdk.model.create_keystone_request import CreateKeystoneRequest


class TestCreateKeystoneRequest(unittest.TestCase):
    """CreateKeystoneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateKeystoneRequest(self):
        """Test CreateKeystoneRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateKeystoneRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
