"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_indexed_object_params import CommonIndexedObjectParams
from cohesity_sdk.cluster.model.document_library_item import DocumentLibraryItem
from cohesity_sdk.cluster.model.email import Email
from cohesity_sdk.cluster.model.ms_group_item_all_of import MsGroupItemAllOf
from cohesity_sdk.cluster.model.snapshot_tag_info import SnapshotTagInfo
from cohesity_sdk.cluster.model.tag_info import TagInfo
globals()['CommonIndexedObjectParams'] = CommonIndexedObjectParams
globals()['DocumentLibraryItem'] = DocumentLibraryItem
globals()['Email'] = Email
globals()['MsGroupItemAllOf'] = MsGroupItemAllOf
globals()['SnapshotTagInfo'] = SnapshotTagInfo
globals()['TagInfo'] = TagInfo
from cohesity_sdk.model.ms_group_item import MsGroupItem


class TestMsGroupItem(unittest.TestCase):
    """MsGroupItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMsGroupItem(self):
        """Test MsGroupItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MsGroupItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
