"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_hyper_v_object_params import CommonHyperVObjectParams
from cohesity_sdk.cluster.model.hyper_v_object_protection_request_all_of import HyperVObjectProtectionRequestAllOf
globals()['CommonHyperVObjectParams'] = CommonHyperVObjectParams
globals()['HyperVObjectProtectionRequestAllOf'] = HyperVObjectProtectionRequestAllOf
from cohesity_sdk.model.hyper_v_object_protection_request import HyperVObjectProtectionRequest


class TestHyperVObjectProtectionRequest(unittest.TestCase):
    """HyperVObjectProtectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHyperVObjectProtectionRequest(self):
        """Test HyperVObjectProtectionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HyperVObjectProtectionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
