"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.mongo_db_protection_group_params_all_of import MongoDBProtectionGroupParamsAllOf
from cohesity_sdk.cluster.model.no_sql_protection_group_object_params import NoSqlProtectionGroupObjectParams
from cohesity_sdk.cluster.model.no_sql_protection_group_params import NoSqlProtectionGroupParams
globals()['MongoDBProtectionGroupParamsAllOf'] = MongoDBProtectionGroupParamsAllOf
globals()['NoSqlProtectionGroupObjectParams'] = NoSqlProtectionGroupObjectParams
globals()['NoSqlProtectionGroupParams'] = NoSqlProtectionGroupParams
from cohesity_sdk.model.mongo_db_protection_group_params import MongoDBProtectionGroupParams


class TestMongoDBProtectionGroupParams(unittest.TestCase):
    """MongoDBProtectionGroupParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMongoDBProtectionGroupParams(self):
        """Test MongoDBProtectionGroupParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MongoDBProtectionGroupParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
