"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.reset_or_restore_networking import ResetOrRestoreNetworking


class TestResetOrRestoreNetworking(unittest.TestCase):
    """ResetOrRestoreNetworking unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetOrRestoreNetworking(self):
        """Test ResetOrRestoreNetworking"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResetOrRestoreNetworking()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
