"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.uda_registration_params_primary_fields_app_authentication import UdaRegistrationParamsPrimaryFieldsAppAuthentication
from cohesity_sdk.cluster.model.uda_registration_params_primary_fields_mount_view import UdaRegistrationParamsPrimaryFieldsMountView
from cohesity_sdk.cluster.model.uda_registration_params_primary_fields_script_dir import UdaRegistrationParamsPrimaryFieldsScriptDir
from cohesity_sdk.cluster.model.uda_registration_params_primary_fields_source_registration_args import UdaRegistrationParamsPrimaryFieldsSourceRegistrationArgs
globals()['UdaRegistrationParamsPrimaryFieldsAppAuthentication'] = UdaRegistrationParamsPrimaryFieldsAppAuthentication
globals()['UdaRegistrationParamsPrimaryFieldsMountView'] = UdaRegistrationParamsPrimaryFieldsMountView
globals()['UdaRegistrationParamsPrimaryFieldsScriptDir'] = UdaRegistrationParamsPrimaryFieldsScriptDir
globals()['UdaRegistrationParamsPrimaryFieldsSourceRegistrationArgs'] = UdaRegistrationParamsPrimaryFieldsSourceRegistrationArgs
from cohesity_sdk.model.uda_registration_params_primary_fields import UdaRegistrationParamsPrimaryFields


class TestUdaRegistrationParamsPrimaryFields(unittest.TestCase):
    """UdaRegistrationParamsPrimaryFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUdaRegistrationParamsPrimaryFields(self):
        """Test UdaRegistrationParamsPrimaryFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UdaRegistrationParamsPrimaryFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
