"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.chassis_rack_config_params import ChassisRackConfigParams
from cohesity_sdk.cluster.model.physical_node_config_params import PhysicalNodeConfigParams
globals()['ChassisRackConfigParams'] = ChassisRackConfigParams
globals()['PhysicalNodeConfigParams'] = PhysicalNodeConfigParams
from cohesity_sdk.model.physical_cluster_expand_params import PhysicalClusterExpandParams


class TestPhysicalClusterExpandParams(unittest.TestCase):
    """PhysicalClusterExpandParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhysicalClusterExpandParams(self):
        """Test PhysicalClusterExpandParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PhysicalClusterExpandParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
