"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_mssql_file_object_protection_params import CommonMssqlFileObjectProtectionParams
from cohesity_sdk.cluster.model.common_mssql_native_object_protection_params import CommonMssqlNativeObjectProtectionParams
from cohesity_sdk.cluster.model.common_mssql_object_protection_params import CommonMssqlObjectProtectionParams
globals()['CommonMssqlFileObjectProtectionParams'] = CommonMssqlFileObjectProtectionParams
globals()['CommonMssqlNativeObjectProtectionParams'] = CommonMssqlNativeObjectProtectionParams
globals()['CommonMssqlObjectProtectionParams'] = CommonMssqlObjectProtectionParams
from cohesity_sdk.model.mssql_object_protection_response_params import MssqlObjectProtectionResponseParams


class TestMssqlObjectProtectionResponseParams(unittest.TestCase):
    """MssqlObjectProtectionResponseParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMssqlObjectProtectionResponseParams(self):
        """Test MssqlObjectProtectionResponseParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MssqlObjectProtectionResponseParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
