"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_tdm_clone_snapshot_params import CommonTdmCloneSnapshotParams
from cohesity_sdk.cluster.model.tdm_snapshot_all_of import TdmSnapshotAllOf
globals()['CommonTdmCloneSnapshotParams'] = CommonTdmCloneSnapshotParams
globals()['TdmSnapshotAllOf'] = TdmSnapshotAllOf
from cohesity_sdk.model.tdm_snapshot import TdmSnapshot


class TestTdmSnapshot(unittest.TestCase):
    """TdmSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTdmSnapshot(self):
        """Test TdmSnapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TdmSnapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
