"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.cassandra_source_config_params import CassandraSourceConfigParams
from cohesity_sdk.cluster.model.h_base_additional_params import HBaseAdditionalParams
from cohesity_sdk.cluster.model.hdfs_additional_params import HdfsAdditionalParams
from cohesity_sdk.cluster.model.hive_additional_params import HiveAdditionalParams
from cohesity_sdk.cluster.model.mssql_connection_response_params import MssqlConnectionResponseParams
from cohesity_sdk.cluster.model.vmware_additional_params import VmwareAdditionalParams
globals()['CassandraSourceConfigParams'] = CassandraSourceConfigParams
globals()['HBaseAdditionalParams'] = HBaseAdditionalParams
globals()['HdfsAdditionalParams'] = HdfsAdditionalParams
globals()['HiveAdditionalParams'] = HiveAdditionalParams
globals()['MssqlConnectionResponseParams'] = MssqlConnectionResponseParams
globals()['VmwareAdditionalParams'] = VmwareAdditionalParams
from cohesity_sdk.model.source_connection_response_params import SourceConnectionResponseParams


class TestSourceConnectionResponseParams(unittest.TestCase):
    """SourceConnectionResponseParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceConnectionResponseParams(self):
        """Test SourceConnectionResponseParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceConnectionResponseParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
