"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_pre_backup_script_params import CommonPreBackupScriptParams
from cohesity_sdk.cluster.model.remote_adapter_host_all_of import RemoteAdapterHostAllOf
from cohesity_sdk.cluster.model.script_host import ScriptHost
globals()['CommonPreBackupScriptParams'] = CommonPreBackupScriptParams
globals()['RemoteAdapterHostAllOf'] = RemoteAdapterHostAllOf
globals()['ScriptHost'] = ScriptHost
from cohesity_sdk.model.remote_adapter_host import RemoteAdapterHost


class TestRemoteAdapterHost(unittest.TestCase):
    """RemoteAdapterHost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteAdapterHost(self):
        """Test RemoteAdapterHost"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoteAdapterHost()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
