"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.cdp_retention import CdpRetention
globals()['CdpRetention'] = CdpRetention
from cohesity_sdk.model.cdp_backup_policy import CdpBackupPolicy


class TestCdpBackupPolicy(unittest.TestCase):
    """CdpBackupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCdpBackupPolicy(self):
        """Test CdpBackupPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CdpBackupPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
