"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.cluster_identifier import ClusterIdentifier
globals()['ClusterIdentifier'] = ClusterIdentifier
from cohesity_sdk.model.cancel_object_run_params import CancelObjectRunParams


class TestCancelObjectRunParams(unittest.TestCase):
    """CancelObjectRunParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelObjectRunParams(self):
        """Test CancelObjectRunParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CancelObjectRunParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
