"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.helios_common_cloud_tier_settings import HeliosCommonCloudTierSettings
from cohesity_sdk.cluster.model.helios_oracle_tier_all_of import HeliosOracleTierAllOf
globals()['HeliosCommonCloudTierSettings'] = HeliosCommonCloudTierSettings
globals()['HeliosOracleTierAllOf'] = HeliosOracleTierAllOf
from cohesity_sdk.model.helios_oracle_tier import HeliosOracleTier


class TestHeliosOracleTier(unittest.TestCase):
    """HeliosOracleTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeliosOracleTier(self):
        """Test HeliosOracleTier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeliosOracleTier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
