"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.filter_ip_config import FilterIpConfig
from cohesity_sdk.cluster.model.recovery_vlan_config import RecoveryVlanConfig
globals()['FilterIpConfig'] = FilterIpConfig
globals()['RecoveryVlanConfig'] = RecoveryVlanConfig
from cohesity_sdk.model.recover_other_nas_to_gpfs_files_target_params import RecoverOtherNasToGpfsFilesTargetParams


class TestRecoverOtherNasToGpfsFilesTargetParams(unittest.TestCase):
    """RecoverOtherNasToGpfsFilesTargetParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverOtherNasToGpfsFilesTargetParams(self):
        """Test RecoverOtherNasToGpfsFilesTargetParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverOtherNasToGpfsFilesTargetParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
