"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.string_form_field_params import StringFormFieldParams


class TestStringFormFieldParams(unittest.TestCase):
    """StringFormFieldParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStringFormFieldParams(self):
        """Test StringFormFieldParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StringFormFieldParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
