"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.file_count import FileCount
from cohesity_sdk.cluster.model.files_stats_for_entity import FilesStatsForEntity
globals()['FileCount'] = FileCount
globals()['FilesStatsForEntity'] = FilesStatsForEntity
from cohesity_sdk.model.files_stats import FilesStats


class TestFilesStats(unittest.TestCase):
    """FilesStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilesStats(self):
        """Test FilesStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilesStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
