"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_object_action_request import CommonObjectActionRequest
from cohesity_sdk.cluster.model.object_action_request_all_of import ObjectActionRequestAllOf
from cohesity_sdk.cluster.model.vmware_object_action_params import VmwareObjectActionParams
globals()['CommonObjectActionRequest'] = CommonObjectActionRequest
globals()['ObjectActionRequestAllOf'] = ObjectActionRequestAllOf
globals()['VmwareObjectActionParams'] = VmwareObjectActionParams
from cohesity_sdk.model.object_action_request import ObjectActionRequest


class TestObjectActionRequest(unittest.TestCase):
    """ObjectActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectActionRequest(self):
        """Test ObjectActionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectActionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
