"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.org_vdc_network import OrgVDCNetwork
from cohesity_sdk.cluster.model.recovery_object_identifier import RecoveryObjectIdentifier
globals()['OrgVDCNetwork'] = OrgVDCNetwork
globals()['RecoveryObjectIdentifier'] = RecoveryObjectIdentifier
from cohesity_sdk.model.recover_vmware_vm_vcd_source_config import RecoverVmwareVmVCDSourceConfig


class TestRecoverVmwareVmVCDSourceConfig(unittest.TestCase):
    """RecoverVmwareVmVCDSourceConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverVmwareVmVCDSourceConfig(self):
        """Test RecoverVmwareVmVCDSourceConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverVmwareVmVCDSourceConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
