"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.recover_uda_params import RecoverUdaParams
globals()['RecoverUdaParams'] = RecoverUdaParams
from cohesity_sdk.model.uda_params import UdaParams


class TestUdaParams(unittest.TestCase):
    """UdaParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUdaParams(self):
        """Test UdaParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UdaParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
