"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.exchange_recover_database_params import ExchangeRecoverDatabaseParams
globals()['ExchangeRecoverDatabaseParams'] = ExchangeRecoverDatabaseParams
from cohesity_sdk.model.recover_exchange_app_snapshot_params_all_of import RecoverExchangeAppSnapshotParamsAllOf


class TestRecoverExchangeAppSnapshotParamsAllOf(unittest.TestCase):
    """RecoverExchangeAppSnapshotParamsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverExchangeAppSnapshotParamsAllOf(self):
        """Test RecoverExchangeAppSnapshotParamsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverExchangeAppSnapshotParamsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
