"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.cassandra_source_registration_patch_params_cassandra_credentials import CassandraSourceRegistrationPatchParamsCassandraCredentials


class TestCassandraSourceRegistrationPatchParamsCassandraCredentials(unittest.TestCase):
    """CassandraSourceRegistrationPatchParamsCassandraCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCassandraSourceRegistrationPatchParamsCassandraCredentials(self):
        """Test CassandraSourceRegistrationPatchParamsCassandraCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CassandraSourceRegistrationPatchParamsCassandraCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
