"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.run_object_physical_params import RunObjectPhysicalParams
globals()['RunObjectPhysicalParams'] = RunObjectPhysicalParams
from cohesity_sdk.model.run_object import RunObject


class TestRunObject(unittest.TestCase):
    """RunObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunObject(self):
        """Test RunObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
