"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.hbase_indexed_object import HbaseIndexedObject
globals()['HbaseIndexedObject'] = HbaseIndexedObject
from cohesity_sdk.model.hbase_indexed_objects import HbaseIndexedObjects


class TestHbaseIndexedObjects(unittest.TestCase):
    """HbaseIndexedObjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHbaseIndexedObjects(self):
        """Test HbaseIndexedObjects"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HbaseIndexedObjects()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
