"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.object_protection_run_summary import ObjectProtectionRunSummary
from cohesity_sdk.cluster.model.protected_object_backup_config import ProtectedObjectBackupConfig
from cohesity_sdk.cluster.model.protected_object_group_backup_config import ProtectedObjectGroupBackupConfig
from cohesity_sdk.cluster.model.tenant import Tenant
globals()['ObjectProtectionRunSummary'] = ObjectProtectionRunSummary
globals()['ProtectedObjectBackupConfig'] = ProtectedObjectBackupConfig
globals()['ProtectedObjectGroupBackupConfig'] = ProtectedObjectGroupBackupConfig
globals()['Tenant'] = Tenant
from cohesity_sdk.model.protected_object_info_all_of import ProtectedObjectInfoAllOf


class TestProtectedObjectInfoAllOf(unittest.TestCase):
    """ProtectedObjectInfoAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtectedObjectInfoAllOf(self):
        """Test ProtectedObjectInfoAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProtectedObjectInfoAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
