"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.local_global_object_ids import LocalGlobalObjectIds
globals()['LocalGlobalObjectIds'] = LocalGlobalObjectIds
from cohesity_sdk.model.local_global_object_id_list import LocalGlobalObjectIdList


class TestLocalGlobalObjectIdList(unittest.TestCase):
    """LocalGlobalObjectIdList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalGlobalObjectIdList(self):
        """Test LocalGlobalObjectIdList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LocalGlobalObjectIdList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
