"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.cassandra_connection_params import CassandraConnectionParams
from cohesity_sdk.cluster.model.common_source_connection_request_params import CommonSourceConnectionRequestParams
from cohesity_sdk.cluster.model.hadoop_connection_params import HadoopConnectionParams
from cohesity_sdk.cluster.model.mssql_connection_params import MssqlConnectionParams
from cohesity_sdk.cluster.model.oracle_connection_params import OracleConnectionParams
from cohesity_sdk.cluster.model.source_connection_request_params_all_of import SourceConnectionRequestParamsAllOf
from cohesity_sdk.cluster.model.vmware_connection_params import VmwareConnectionParams
globals()['CassandraConnectionParams'] = CassandraConnectionParams
globals()['CommonSourceConnectionRequestParams'] = CommonSourceConnectionRequestParams
globals()['HadoopConnectionParams'] = HadoopConnectionParams
globals()['MssqlConnectionParams'] = MssqlConnectionParams
globals()['OracleConnectionParams'] = OracleConnectionParams
globals()['SourceConnectionRequestParamsAllOf'] = SourceConnectionRequestParamsAllOf
globals()['VmwareConnectionParams'] = VmwareConnectionParams
from cohesity_sdk.model.source_connection_request_params import SourceConnectionRequestParams


class TestSourceConnectionRequestParams(unittest.TestCase):
    """SourceConnectionRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceConnectionRequestParams(self):
        """Test SourceConnectionRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SourceConnectionRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
