"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.file_count import FileCount
from cohesity_sdk.cluster.model.schema import Schema
from cohesity_sdk.cluster.model.subnet import Subnet
globals()['FileCount'] = FileCount
globals()['Schema'] = Schema
globals()['Subnet'] = Subnet
from cohesity_sdk.model.storage_domain import StorageDomain


class TestStorageDomain(unittest.TestCase):
    """StorageDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageDomain(self):
        """Test StorageDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StorageDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
