"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.cluster_create_network_config import ClusterCreateNetworkConfig
from cohesity_sdk.cluster.model.cluster_proxy_server_config import ClusterProxyServerConfig
from cohesity_sdk.cluster.model.helios_on_prem_ssh_config import HeliosOnPremSSHConfig
from cohesity_sdk.cluster.model.helios_on_prem_vm_node import HeliosOnPremVMNode
globals()['ClusterCreateNetworkConfig'] = ClusterCreateNetworkConfig
globals()['ClusterProxyServerConfig'] = ClusterProxyServerConfig
globals()['HeliosOnPremSSHConfig'] = HeliosOnPremSSHConfig
globals()['HeliosOnPremVMNode'] = HeliosOnPremVMNode
from cohesity_sdk.model.helios_on_prem_config import HeliosOnPremConfig


class TestHeliosOnPremConfig(unittest.TestCase):
    """HeliosOnPremConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeliosOnPremConfig(self):
        """Test HeliosOnPremConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeliosOnPremConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
