"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.recover_protection_group_run_params import RecoverProtectionGroupRunParams
globals()['RecoverProtectionGroupRunParams'] = RecoverProtectionGroupRunParams
from cohesity_sdk.model.recover_aws_s3_bucket_params import RecoverAwsS3BucketParams


class TestRecoverAwsS3BucketParams(unittest.TestCase):
    """RecoverAwsS3BucketParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverAwsS3BucketParams(self):
        """Test RecoverAwsS3BucketParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverAwsS3BucketParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
