"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.credentials import Credentials
from cohesity_sdk.cluster.model.filter_ip_config import FilterIpConfig
from cohesity_sdk.cluster.model.nas_throttling_config import NasThrottlingConfig
globals()['Credentials'] = Credentials
globals()['FilterIpConfig'] = FilterIpConfig
globals()['NasThrottlingConfig'] = NasThrottlingConfig
from cohesity_sdk.model.gpfs_registration_params import GpfsRegistrationParams


class TestGpfsRegistrationParams(unittest.TestCase):
    """GpfsRegistrationParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGpfsRegistrationParams(self):
        """Test GpfsRegistrationParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GpfsRegistrationParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
