"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.advanced_settings import AdvancedSettings
from cohesity_sdk.cluster.model.common_mssql_native_object_protection_params_all_of import CommonMssqlNativeObjectProtectionParamsAllOf
from cohesity_sdk.cluster.model.common_mssql_protection_group_params import CommonMSSQLProtectionGroupParams
from cohesity_sdk.cluster.model.filter import Filter
from cohesity_sdk.cluster.model.pre_post_script_params import PrePostScriptParams
globals()['AdvancedSettings'] = AdvancedSettings
globals()['CommonMSSQLProtectionGroupParams'] = CommonMSSQLProtectionGroupParams
globals()['CommonMssqlNativeObjectProtectionParamsAllOf'] = CommonMssqlNativeObjectProtectionParamsAllOf
globals()['Filter'] = Filter
globals()['PrePostScriptParams'] = PrePostScriptParams
from cohesity_sdk.model.common_mssql_native_object_protection_params import CommonMssqlNativeObjectProtectionParams


class TestCommonMssqlNativeObjectProtectionParams(unittest.TestCase):
    """CommonMssqlNativeObjectProtectionParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonMssqlNativeObjectProtectionParams(self):
        """Test CommonMssqlNativeObjectProtectionParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonMssqlNativeObjectProtectionParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
