"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.es_config_for_indexing import ESConfigForIndexing


class TestESConfigForIndexing(unittest.TestCase):
    """ESConfigForIndexing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testESConfigForIndexing(self):
        """Test ESConfigForIndexing"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ESConfigForIndexing()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
