"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.entity_identifier import EntityIdentifier
globals()['EntityIdentifier'] = EntityIdentifier
from cohesity_sdk.model.workload_sub_type_all_of import WorkloadSubTypeAllOf


class TestWorkloadSubTypeAllOf(unittest.TestCase):
    """WorkloadSubTypeAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkloadSubTypeAllOf(self):
        """Test WorkloadSubTypeAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkloadSubTypeAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
