"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.public_folder_item_all_of import PublicFolderItemAllOf


class TestPublicFolderItemAllOf(unittest.TestCase):
    """PublicFolderItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicFolderItemAllOf(self):
        """Test PublicFolderItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PublicFolderItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
