"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.helios_full_backup_policy import HeliosFullBackupPolicy
from cohesity_sdk.cluster.model.helios_incremental_backup_policy import HeliosIncrementalBackupPolicy
from cohesity_sdk.cluster.model.helios_primary_backup_target import HeliosPrimaryBackupTarget
from cohesity_sdk.cluster.model.helios_retention import HeliosRetention
globals()['HeliosFullBackupPolicy'] = HeliosFullBackupPolicy
globals()['HeliosIncrementalBackupPolicy'] = HeliosIncrementalBackupPolicy
globals()['HeliosPrimaryBackupTarget'] = HeliosPrimaryBackupTarget
globals()['HeliosRetention'] = HeliosRetention
from cohesity_sdk.model.helios_regular_backup_policy import HeliosRegularBackupPolicy


class TestHeliosRegularBackupPolicy(unittest.TestCase):
    """HeliosRegularBackupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeliosRegularBackupPolicy(self):
        """Test HeliosRegularBackupPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeliosRegularBackupPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
