"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.alert_target import AlertTarget
globals()['AlertTarget'] = AlertTarget
from cohesity_sdk.model.protection_group_alerting_policy import ProtectionGroupAlertingPolicy


class TestProtectionGroupAlertingPolicy(unittest.TestCase):
    """ProtectionGroupAlertingPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtectionGroupAlertingPolicy(self):
        """Test ProtectionGroupAlertingPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProtectionGroupAlertingPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
