"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.client_stats_in_last_hours import ClientStatsInLastHours
globals()['ClientStatsInLastHours'] = ClientStatsInLastHours
from cohesity_sdk.model.client_stats import ClientStats


class TestClientStats(unittest.TestCase):
    """ClientStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientStats(self):
        """Test ClientStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClientStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
