"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.incremental_schedule import IncrementalSchedule
globals()['IncrementalSchedule'] = IncrementalSchedule
from cohesity_sdk.model.incremental_backup_policy import IncrementalBackupPolicy


class TestIncrementalBackupPolicy(unittest.TestCase):
    """IncrementalBackupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncrementalBackupPolicy(self):
        """Test IncrementalBackupPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncrementalBackupPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
