"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.hbase_source_registration_params_all_of_ssh_password_credentials import HbaseSourceRegistrationParamsAllOfSshPasswordCredentials
from cohesity_sdk.cluster.model.hbase_source_registration_params_all_of_ssh_private_key_credentials import HbaseSourceRegistrationParamsAllOfSshPrivateKeyCredentials
globals()['HbaseSourceRegistrationParamsAllOfSshPasswordCredentials'] = HbaseSourceRegistrationParamsAllOfSshPasswordCredentials
globals()['HbaseSourceRegistrationParamsAllOfSshPrivateKeyCredentials'] = HbaseSourceRegistrationParamsAllOfSshPrivateKeyCredentials
from cohesity_sdk.model.hdfs_source_registration_params_all_of import HdfsSourceRegistrationParamsAllOf


class TestHdfsSourceRegistrationParamsAllOf(unittest.TestCase):
    """HdfsSourceRegistrationParamsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHdfsSourceRegistrationParamsAllOf(self):
        """Test HdfsSourceRegistrationParamsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HdfsSourceRegistrationParamsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
