"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.failover import Failover
globals()['Failover'] = Failover
from cohesity_sdk.model.get_view_failover_response_body import GetViewFailoverResponseBody


class TestGetViewFailoverResponseBody(unittest.TestCase):
    """GetViewFailoverResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetViewFailoverResponseBody(self):
        """Test GetViewFailoverResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetViewFailoverResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
