"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.data_tiering_analysis_share_info import DataTieringAnalysisShareInfo
globals()['DataTieringAnalysisShareInfo'] = DataTieringAnalysisShareInfo
from cohesity_sdk.model.data_tiering_analysis_run_request import DataTieringAnalysisRunRequest


class TestDataTieringAnalysisRunRequest(unittest.TestCase):
    """DataTieringAnalysisRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataTieringAnalysisRunRequest(self):
        """Test DataTieringAnalysisRunRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataTieringAnalysisRunRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
