"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.helios_azure_tier import HeliosAzureTier
globals()['HeliosAzureTier'] = HeliosAzureTier
from cohesity_sdk.model.helios_azure_tiers import HeliosAzureTiers


class TestHeliosAzureTiers(unittest.TestCase):
    """HeliosAzureTiers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeliosAzureTiers(self):
        """Test HeliosAzureTiers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HeliosAzureTiers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
