"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.clone_view_directory_params import CloneViewDirectoryParams


class TestCloneViewDirectoryParams(unittest.TestCase):
    """CloneViewDirectoryParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloneViewDirectoryParams(self):
        """Test CloneViewDirectoryParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloneViewDirectoryParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
