"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.bmr_backup_policy import BmrBackupPolicy
from cohesity_sdk.cluster.model.cancellation_timeout_params import CancellationTimeoutParams
from cohesity_sdk.cluster.model.cdp_backup_policy import CdpBackupPolicy
from cohesity_sdk.cluster.model.log_backup_policy import LogBackupPolicy
from cohesity_sdk.cluster.model.regular_backup_policy import RegularBackupPolicy
from cohesity_sdk.cluster.model.storage_array_snapshot_backup_policy import StorageArraySnapshotBackupPolicy
globals()['BmrBackupPolicy'] = BmrBackupPolicy
globals()['CancellationTimeoutParams'] = CancellationTimeoutParams
globals()['CdpBackupPolicy'] = CdpBackupPolicy
globals()['LogBackupPolicy'] = LogBackupPolicy
globals()['RegularBackupPolicy'] = RegularBackupPolicy
globals()['StorageArraySnapshotBackupPolicy'] = StorageArraySnapshotBackupPolicy
from cohesity_sdk.model.backup_policy import BackupPolicy


class TestBackupPolicy(unittest.TestCase):
    """BackupPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupPolicy(self):
        """Test BackupPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BackupPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
