"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.protected_object_pause_action_params import ProtectedObjectPauseActionParams
from cohesity_sdk.cluster.model.protected_object_resume_action_params import ProtectedObjectResumeActionParams
from cohesity_sdk.cluster.model.protected_object_run_now_action_params import ProtectedObjectRunNowActionParams
from cohesity_sdk.cluster.model.protected_object_un_protect_action_params import ProtectedObjectUnProtectActionParams
globals()['ProtectedObjectPauseActionParams'] = ProtectedObjectPauseActionParams
globals()['ProtectedObjectResumeActionParams'] = ProtectedObjectResumeActionParams
globals()['ProtectedObjectRunNowActionParams'] = ProtectedObjectRunNowActionParams
globals()['ProtectedObjectUnProtectActionParams'] = ProtectedObjectUnProtectActionParams
from cohesity_sdk.model.protectd_objects_action_request import ProtectdObjectsActionRequest


class TestProtectdObjectsActionRequest(unittest.TestCase):
    """ProtectdObjectsActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProtectdObjectsActionRequest(self):
        """Test ProtectdObjectsActionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProtectdObjectsActionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
