"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.onprem_deploy_params import OnpremDeployParams
globals()['OnpremDeployParams'] = OnpremDeployParams
from cohesity_sdk.model.onprem_deploy_config_all_of import OnpremDeployConfigAllOf


class TestOnpremDeployConfigAllOf(unittest.TestCase):
    """OnpremDeployConfigAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnpremDeployConfigAllOf(self):
        """Test OnpremDeployConfigAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OnpremDeployConfigAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
