"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import cohesity_sdk
from cohesity_sdk.api.ips import IPsApi  # noqa: E501


class TestIPsApi(unittest.TestCase):
    """IPsApi unit test stubs"""

    def setUp(self):
        self.api = IPsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configure_ip_settings(self):
        """Test case for configure_ip_settings

        Configure an IP setting.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
