"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_pre_post_cloud_script_params import CommonPrePostCloudScriptParams
globals()['CommonPrePostCloudScriptParams'] = CommonPrePostCloudScriptParams
from cohesity_sdk.model.cloud_backup_script_params import CloudBackupScriptParams


class TestCloudBackupScriptParams(unittest.TestCase):
    """CloudBackupScriptParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudBackupScriptParams(self):
        """Test CloudBackupScriptParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CloudBackupScriptParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
