"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.common_gcp_external_target_params import CommonGcpExternalTargetParams


class TestCommonGcpExternalTargetParams(unittest.TestCase):
    """CommonGcpExternalTargetParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonGcpExternalTargetParams(self):
        """Test CommonGcpExternalTargetParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommonGcpExternalTargetParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
