"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.recover_couchbase_params import RecoverCouchbaseParams
globals()['RecoverCouchbaseParams'] = RecoverCouchbaseParams
from cohesity_sdk.model.couchbase_params import CouchbaseParams


class TestCouchbaseParams(unittest.TestCase):
    """CouchbaseParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCouchbaseParams(self):
        """Test CouchbaseParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CouchbaseParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
