"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.recover_target import RecoverTarget
globals()['RecoverTarget'] = RecoverTarget
from cohesity_sdk.model.physical_mount_volumes_new_target_config import PhysicalMountVolumesNewTargetConfig


class TestPhysicalMountVolumesNewTargetConfig(unittest.TestCase):
    """PhysicalMountVolumesNewTargetConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhysicalMountVolumesNewTargetConfig(self):
        """Test PhysicalMountVolumesNewTargetConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PhysicalMountVolumesNewTargetConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
