"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.o365_search_request_params import O365SearchRequestParams


class TestO365SearchRequestParams(unittest.TestCase):
    """O365SearchRequestParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testO365SearchRequestParams(self):
        """Test O365SearchRequestParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = O365SearchRequestParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
