"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.mssql_file_protection_group_params import MSSQLFileProtectionGroupParams
from cohesity_sdk.cluster.model.mssql_native_protection_group_params import MSSQLNativeProtectionGroupParams
from cohesity_sdk.cluster.model.mssql_volume_protection_group_params import MSSQLVolumeProtectionGroupParams
globals()['MSSQLFileProtectionGroupParams'] = MSSQLFileProtectionGroupParams
globals()['MSSQLNativeProtectionGroupParams'] = MSSQLNativeProtectionGroupParams
globals()['MSSQLVolumeProtectionGroupParams'] = MSSQLVolumeProtectionGroupParams
from cohesity_sdk.model.mssql_protection_group_params import MSSQLProtectionGroupParams


class TestMSSQLProtectionGroupParams(unittest.TestCase):
    """MSSQLProtectionGroupParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMSSQLProtectionGroupParams(self):
        """Test MSSQLProtectionGroupParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MSSQLProtectionGroupParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
