"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_oracle_clone_params import CommonOracleCloneParams
from cohesity_sdk.cluster.model.oracle_clone_object_all_of import OracleCloneObjectAllOf
globals()['CommonOracleCloneParams'] = CommonOracleCloneParams
globals()['OracleCloneObjectAllOf'] = OracleCloneObjectAllOf
from cohesity_sdk.model.oracle_clone_object import OracleCloneObject


class TestOracleCloneObject(unittest.TestCase):
    """OracleCloneObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOracleCloneObject(self):
        """Test OracleCloneObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OracleCloneObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
