"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.channel_item import ChannelItem
from cohesity_sdk.cluster.model.teams_file_item import TeamsFileItem
globals()['ChannelItem'] = ChannelItem
globals()['TeamsFileItem'] = TeamsFileItem
from cohesity_sdk.model.teams_item_all_of import TeamsItemAllOf


class TestTeamsItemAllOf(unittest.TestCase):
    """TeamsItemAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamsItemAllOf(self):
        """Test TeamsItemAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TeamsItemAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
