"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.model.mcm_claim_entity_type import McmClaimEntityType


class TestMcmClaimEntityType(unittest.TestCase):
    """McmClaimEntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMcmClaimEntityType(self):
        """Test McmClaimEntityType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = McmClaimEntityType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
