"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cohesity_sdk
from cohesity_sdk.cluster.model.common_recover_object_snapshot_params import CommonRecoverObjectSnapshotParams
from cohesity_sdk.cluster.model.recover_uda_object_params import RecoverUdaObjectParams
from cohesity_sdk.cluster.model.recover_uda_snapshot_params_all_of import RecoverUdaSnapshotParamsAllOf
globals()['CommonRecoverObjectSnapshotParams'] = CommonRecoverObjectSnapshotParams
globals()['RecoverUdaObjectParams'] = RecoverUdaObjectParams
globals()['RecoverUdaSnapshotParamsAllOf'] = RecoverUdaSnapshotParamsAllOf
from cohesity_sdk.model.recover_uda_snapshot_params import RecoverUdaSnapshotParams


class TestRecoverUdaSnapshotParams(unittest.TestCase):
    """RecoverUdaSnapshotParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverUdaSnapshotParams(self):
        """Test RecoverUdaSnapshotParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverUdaSnapshotParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
