__MAJOR__ = 0
__MINOR__ = 1
__MICRO__ = 10
__RELEASE__ = ''  # a #b  # https://www.python.org/dev/peps/pep-0440/#public-version-identifiers --> alpha beta, ...
__VERSION__ = ''.join([str(__MAJOR__), '.', str(__MINOR__), '.', str(__MICRO__)])
__DESCRIPTION__ = """An aggregate of functions I find useful"""
__URL__ = 'https://github.com/baigouy/batoolset'
__EMAIL__ = 'benoit.aigouy@gmail.com'
__AUTHOR__ = 'Benoit Aigouy'
