# Environment variables
PAI_PIPELINE_METADATA_IDENTIFIER = "PAI_PIPELINE_METADATA_IDENTIFIER"
PAI_USER_ID = "PAI_USER_ID"
PAI_MLFLOW_LOG_METRIC_TO_PARENT_RUN = "PAI_MLFLOW_LOG_METRIC_TO_PARENT_RUN"
PAI_MLFLOW_PARENT_RUN_ID = "PAI_MLFLOW_PARENT_RUN_ID"
PAI_MLFLOW_RUN_NAME = "PAI_MLFLOW_RUN_NAME"
PAI_STUDIO_EXPERIMENT_ID = "PAI_STUDIO_EXPERIMENT_ID"
PAI_RUN_ID = "PAI_RUN_ID"
PAI_NODE_ID = "PAI_NODE_ID"
PAI_PAIFLOW_PIPELINES = "PAI_PAIFLOW_PIPELINES"
PAI_AI_WORKSPACE_ID = "PAI_AI_WORKSPACE_ID"

# MLflow run source
SOURCE_PAI_STUDIO = "PAI_STUDIO"
