from wiederverwendbar.functions.admin import is_admin, require_admin
from wiederverwendbar.functions.animal_name_generator import animal_name_generator
from wiederverwendbar.functions.eval import eval_value, eval_file
from wiederverwendbar.functions.find_class_method import find_class_method
from wiederverwendbar.functions.wait_ping import wait_ping
