# coding: utf-8

# flake8: noqa

"""
    Test Automation (No submodules)

    SDKs (no submodules) to test automation workflows.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.11"

# import ApiClient
from automation_test_with_submodule.api_client import ApiClient

# import Configuration
from automation_test_with_submodule.configuration import Configuration

# import exceptions
from automation_test_with_submodule.exceptions import OpenApiException
from automation_test_with_submodule.exceptions import ApiAttributeError
from automation_test_with_submodule.exceptions import ApiTypeError
from automation_test_with_submodule.exceptions import ApiValueError
from automation_test_with_submodule.exceptions import ApiKeyError
from automation_test_with_submodule.exceptions import ApiException

from automation_test_with_submodule.client import AutomationTestWithSubmodule
