
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-26T18:42:50+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa51ff22dbfb5644554436270deaf57a7ebaf066",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
