from . import pattern1
from . import pattern2
from . import pattern3
from . import pattern4
from . import pattern5
from . import pattern6
from . import pattern7
from . import pattern8
from . import pattern9
from . import pattern10
from . import pattern11
from . import pattern12
from . import pattern13
from . import pattern14
from . import pattern15
from . import pattern16
from . import pattern17
from . import pattern18
from . import pattern19