class CliError(RuntimeError): ...


class VersionError(ValueError): ...


class VersionMismatchError(VersionError): ...


class VersionConversionError(VersionError): ...


class TargetAlreadyReleasedError(RuntimeError): ...
