
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-29T17:50:16-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe06f06912d6eeb3042407fd995d51f6c58727bd",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
